# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Check_Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication,
    QMainWindow,
    QMessageBox,
    QFileDialog,
    QTableWidget,
)


class Ui_Check_Message(object):
    def setupUi(self, Check_Message):
        Check_Message.setObjectName("Check_Message")
        Check_Message.resize(808, 569)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Check_Message.setFont(font)
        self.text_Message = QtWidgets.QTextEdit(Check_Message)
        self.text_Message.setGeometry(QtCore.QRect(30, 280, 751, 131))
        self.text_Message.setObjectName("text_Message")
        self.pushButton_Private_Key_Location = QtWidgets.QPushButton(Check_Message)
        self.pushButton_Private_Key_Location.setGeometry(QtCore.QRect(40, 430, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButton_Private_Key_Location.setFont(font)
        self.pushButton_Private_Key_Location.setAutoDefault(False)
        self.pushButton_Private_Key_Location.setDefault(False)
        self.pushButton_Private_Key_Location.setFlat(False)
        self.pushButton_Private_Key_Location.setObjectName(
            "pushButton_Private_Key_Location"
        )
        self.label_Private_Key_Location = QtWidgets.QLabel(Check_Message)
        self.label_Private_Key_Location.setGeometry(QtCore.QRect(200, 430, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_Private_Key_Location.setFont(font)
        self.label_Private_Key_Location.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_Private_Key_Location.setObjectName("label_Private_Key_Location")
        self.pushButton_Decrypt = QtWidgets.QPushButton(Check_Message)
        self.pushButton_Decrypt.setGeometry(QtCore.QRect(620, 470, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Decrypt.setFont(font)
        self.pushButton_Decrypt.setAutoDefault(False)
        self.pushButton_Decrypt.setDefault(False)
        self.pushButton_Decrypt.setFlat(False)
        self.pushButton_Decrypt.setObjectName("pushButton_Decrypt")
        self.pushButton_Validate = QtWidgets.QPushButton(Check_Message)
        self.pushButton_Validate.setGeometry(QtCore.QRect(620, 510, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Validate.setFont(font)
        self.pushButton_Validate.setAutoDefault(False)
        self.pushButton_Validate.setDefault(False)
        self.pushButton_Validate.setFlat(False)
        self.pushButton_Validate.setObjectName("pushButton_Validate")
        self.pushButton_Download_The_File = QtWidgets.QPushButton(Check_Message)
        self.pushButton_Download_The_File.setGeometry(QtCore.QRect(40, 470, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButton_Download_The_File.setFont(font)
        self.pushButton_Download_The_File.setAcceptDrops(False)
        self.pushButton_Download_The_File.setAutoDefault(False)
        self.pushButton_Download_The_File.setDefault(False)
        self.pushButton_Download_The_File.setFlat(False)
        self.pushButton_Download_The_File.setObjectName("pushButton_Download_The_File")
        self.scrollArea_message = QtWidgets.QScrollArea(Check_Message)
        self.scrollArea_message.setGeometry(QtCore.QRect(30, 30, 751, 191))
        self.scrollArea_message.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_message.setWidgetResizable(True)
        self.scrollArea_message.setObjectName("scrollArea_message")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget_Message = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_Message.setGeometry(QtCore.QRect(0, 0, 751, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget_Message.setFont(font)
        self.tableWidget_Message.setLineWidth(1)
        self.tableWidget_Message.setMidLineWidth(0)
        self.tableWidget_Message.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Message.setObjectName("tableWidget_Message")

        # set column 4
        self.tableWidget_Message.setColumnCount(4)

        # init set row 0
        self.tableWidget_Message.setRowCount(0)

        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_Message.setVerticalHeaderItem(6, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_Message.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Message.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Message.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_Message.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_Message.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)

        # table set item
        self.tableWidget_Message.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_Message.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableWidget_Message.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)

        self.tableWidget_Message.horizontalHeader().setVisible(True)
        self.tableWidget_Message.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_Message.horizontalHeader().setDefaultSectionSize(176)
        self.tableWidget_Message.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Message.horizontalHeader().setMinimumSectionSize(38)
        self.tableWidget_Message.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_Message.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_Message.verticalHeader().setVisible(True)
        self.tableWidget_Message.verticalHeader().setDefaultSectionSize(30)
        self.scrollArea_message.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(Check_Message)
        self.label.setGeometry(QtCore.QRect(30, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Check_Message)
        QtCore.QMetaObject.connectSlotsByName(Check_Message)

        self.pushButton_Private_Key_Location.clicked.connect(self.select_private_key)

    def retranslateUi(self, Check_Message):
        # table edition is not allowed
        self.tableWidget_Message.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        # set row selection behavior
        self.tableWidget_Message.setSelectionBehavior(QTableWidget.SelectRows)

        _translate = QtCore.QCoreApplication.translate
        Check_Message.setWindowTitle(_translate("Check_Message", "Check Message"))
        self.pushButton_Private_Key_Location.setText(
            _translate("Check_Message", "Select private key")
        )
        self.label_Private_Key_Location.setText(
            _translate("Check_Message", "file/photo.jpg")
        )
        self.pushButton_Decrypt.setText(_translate("Check_Message", "Decrypt"))
        self.pushButton_Validate.setText(_translate("Check_Message", "Validate"))
        self.pushButton_Download_The_File.setText(
            _translate("Check_Message", "Download the file")
        )
        self.tableWidget_Message.setSortingEnabled(True)
        # item = self.tableWidget_Message.verticalHeaderItem(0)
        # item.setText(_translate("Check_Message", "1"))
        # item = self.tableWidget_Message.verticalHeaderItem(1)
        # item.setText(_translate("Check_Message", "2"))
        # item = self.tableWidget_Message.verticalHeaderItem(2)
        # item.setText(_translate("Check_Message", "3"))
        # item = self.tableWidget_Message.verticalHeaderItem(3)
        # item.setText(_translate("Check_Message", "4"))
        # item = self.tableWidget_Message.verticalHeaderItem(4)
        # item.setText(_translate("Check_Message", "5"))
        # item = self.tableWidget_Message.verticalHeaderItem(5)
        # item.setText(_translate("Check_Message", "6"))
        # item = self.tableWidget_Message.verticalHeaderItem(6)
        # item.setText(_translate("Check_Message", "7"))
        item = self.tableWidget_Message.horizontalHeaderItem(0)
        item.setText(_translate("Check_Message", "Sender"))
        item = self.tableWidget_Message.horizontalHeaderItem(1)
        item.setText(_translate("Check_Message", "Message_Type"))
        item = self.tableWidget_Message.horizontalHeaderItem(2)
        item.setText(_translate("Check_Message", "TimeStamp"))
        item = self.tableWidget_Message.horizontalHeaderItem(3)
        item.setText(_translate("Check_Message", "Delivery_Type"))
        __sortingEnabled = self.tableWidget_Message.isSortingEnabled()
        self.tableWidget_Message.setSortingEnabled(False)

        # item = self.tableWidget_Message.item(0, 0)
        # item.setText(_translate("Check_Message", "YYGzzzzzzzzzz"))
        # item = self.tableWidget_Message.item(0, 1)
        # item.setText(_translate("Check_Message", "text"))
        # item = self.tableWidget_Message.item(0, 2)
        # item.setText(_translate("Check_Message", "2022-11-03 03:03:49"))
        # item = self.tableWidget_Message.item(0, 3)
        # item.setText(_translate("Check_Message", "ENCRYPTED_AND_SIGNED"))
        self.tableWidget_Message.setSortingEnabled(__sortingEnabled)

        self.label.setText(_translate("Check_Message", "Message"))

    # select and set the private key path
    def select_private_key(self):
        fname = QFileDialog.getOpenFileName(
            None,
            "Open file",
            "C:",
            "Files (*.pem)",
        )
        self.label_Private_Key_Location.setText(fname[0])

    def show_info(self, info):
        msg_box = QMessageBox()
        msg_box.setWindowTitle("Download Information")
        msg_box.setText(info)
        x = msg_box.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Check_Message = QtWidgets.QWidget()
    ui = Ui_Check_Message()
    ui.setupUi(Check_Message)
    Check_Message.show()
    sys.exit(app.exec_())
