# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(593, 474)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        Login.setFont(font)
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(250, 20, 81, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textStudentID = QtWidgets.QTextEdit(Login)
        self.textStudentID.setGeometry(QtCore.QRect(60, 140, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.textStudentID.setFont(font)
        self.textStudentID.setObjectName("textStudentID")
        self.textPassword = QtWidgets.QTextEdit(Login)
        self.textPassword.setGeometry(QtCore.QRect(60, 240, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.textPassword.setFont(font)
        self.textPassword.setObjectName("textPassword")
        self.btnLogin = QtWidgets.QPushButton(Login)
        self.btnLogin.setGeometry(QtCore.QRect(60, 340, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.btnLogin.setObjectName("btnLogin")
        self.label_4 = QtWidgets.QLabel(Login)
        self.label_4.setGeometry(QtCore.QRect(160, 420, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(Login)
        self.checkBox.setGeometry(QtCore.QRect(60, 310, 191, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.forgetPasswordButton = QtWidgets.QPushButton(Login)
        self.forgetPasswordButton.setGeometry(QtCore.QRect(370, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.forgetPasswordButton.setFont(font)
        self.forgetPasswordButton.setStyleSheet("color: rgb(0, 85, 255);")
        self.forgetPasswordButton.setFlat(True)
        self.forgetPasswordButton.setObjectName("forgetPasswordButton")
        self.registerButton = QtWidgets.QPushButton(Login)
        self.registerButton.setGeometry(QtCore.QRect(330, 420, 81, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("color: rgb(0, 85, 255);")
        self.registerButton.setFlat(True)
        self.registerButton.setObjectName("registerButton")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

        self.registerButton.clicked.connect(self.registerEven)
        self.btnLogin.clicked.connect(self.btnLoginEven)
        self.forgetPasswordButton.clicked.connect(self.forgetPasswordEven)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Student name"))
        self.label_3.setText(_translate("Login", "Password"))
        self.textPassword.setHtml(_translate("Login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnLogin.setText(_translate("Login", "Login"))
        self.label_4.setText(_translate("Login", "Don\'t have an account? "))
        self.checkBox.setText(_translate("Login", "Save the password"))
        self.forgetPasswordButton.setText(_translate("Login", "Forget the password"))
        self.registerButton.setText(_translate("Login", "Register"))

    def forgetPasswordEven(self):
        print('忘记密码')

    def btnLoginEven(self):
        print('登陆点击')

    def registerEven(self):
        print('注册点击')
