# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_Up.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox


class Ui_Sign_Up(object):
    def setupUi(self, Sign_Up):
        Sign_Up.setObjectName("Sign_Up")
        Sign_Up.resize(556, 931)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        Sign_Up.setFont(font)
        self.label_Sign_Up = QtWidgets.QLabel(Sign_Up)
        self.label_Sign_Up.setGeometry(QtCore.QRect(40, 10, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Sign_Up.setFont(font)
        self.label_Sign_Up.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Sign_Up.setObjectName("label_Sign_Up")
        self.label_Username = QtWidgets.QLabel(Sign_Up)
        self.label_Username.setGeometry(QtCore.QRect(40, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_Username.setFont(font)
        self.label_Username.setObjectName("label_Username")
        self.label_Password = QtWidgets.QLabel(Sign_Up)
        self.label_Password.setGeometry(QtCore.QRect(40, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.pushButton_Sign_Up = QtWidgets.QPushButton(Sign_Up)
        self.pushButton_Sign_Up.setGeometry(QtCore.QRect(40, 870, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_Sign_Up.setFont(font)
        self.pushButton_Sign_Up.setStyleSheet(
            "color: rgb(255, 255, 255);\n" "background-color: rgb(0, 85, 255);"
        )
        self.pushButton_Sign_Up.setObjectName("pushButton_Sign_Up")
        self.label_Check_Password = QtWidgets.QLabel(Sign_Up)
        self.label_Check_Password.setGeometry(QtCore.QRect(40, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Check_Password.setFont(font)
        self.label_Check_Password.setObjectName("label_Check_Password")
        self.label_Wallet_Private_Key = QtWidgets.QLabel(Sign_Up)
        self.label_Wallet_Private_Key.setGeometry(QtCore.QRect(40, 430, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Wallet_Private_Key.setFont(font)
        self.label_Wallet_Private_Key.setObjectName("label_Wallet_Private_Key")
        self.label_Email = QtWidgets.QLabel(Sign_Up)
        self.label_Email.setGeometry(QtCore.QRect(40, 540, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Email.setFont(font)
        self.label_Email.setObjectName("label_Email")
        self.label_Phone_Number = QtWidgets.QLabel(Sign_Up)
        self.label_Phone_Number.setGeometry(QtCore.QRect(40, 650, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Phone_Number.setFont(font)
        self.label_Phone_Number.setObjectName("label_Phone_Number")
        self.lineEdit_Check_Password = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Check_Password.setGeometry(QtCore.QRect(40, 360, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Check_Password.setFont(font)
        self.lineEdit_Check_Password.setObjectName("lineEdit_Check_Password")
        self.lineEdit_Username = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Username.setGeometry(QtCore.QRect(40, 150, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Username.setFont(font)
        self.lineEdit_Username.setPlaceholderText("")
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Password.setGeometry(QtCore.QRect(40, 250, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setPlaceholderText("")
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.lineEdit_Wallet_Private_Key = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Wallet_Private_Key.setGeometry(QtCore.QRect(40, 470, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Wallet_Private_Key.setFont(font)
        self.lineEdit_Wallet_Private_Key.setPlaceholderText("")
        self.lineEdit_Wallet_Private_Key.setObjectName("lineEdit_Wallet_Private_Key")
        self.lineEdit_Email = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Email.setGeometry(QtCore.QRect(40, 580, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Email.setFont(font)
        self.lineEdit_Email.setPlaceholderText("")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.lineEdit_Phone_Number = QtWidgets.QLineEdit(Sign_Up)
        self.lineEdit_Phone_Number.setGeometry(QtCore.QRect(40, 690, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_Phone_Number.setFont(font)
        self.lineEdit_Phone_Number.setPlaceholderText("")
        self.lineEdit_Phone_Number.setObjectName("lineEdit_Phone_Number")
        self.label_RSA_Key_Pairs_Length = QtWidgets.QLabel(Sign_Up)
        self.label_RSA_Key_Pairs_Length.setGeometry(QtCore.QRect(40, 760, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_RSA_Key_Pairs_Length.setFont(font)
        self.label_RSA_Key_Pairs_Length.setObjectName("label_RSA_Key_Pairs_Length")
        self.label_Have_A_Account = QtWidgets.QLabel(Sign_Up)
        self.label_Have_A_Account.setGeometry(QtCore.QRect(40, 830, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Have_A_Account.setFont(font)
        self.label_Have_A_Account.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_Have_A_Account.setObjectName("label_Have_A_Account")
        self.pushButton_Login = QtWidgets.QPushButton(Sign_Up)
        self.pushButton_Login.setGeometry(QtCore.QRect(340, 830, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_Login.setFont(font)
        self.pushButton_Login.setStyleSheet("color: rgb(85, 170, 255);")
        self.pushButton_Login.setFlat(True)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.label_notification = QtWidgets.QLabel(Sign_Up)
        self.label_notification.setGeometry(QtCore.QRect(40, 70, 471, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_notification.setFont(font)
        self.label_notification.setObjectName("label_notification")
        self.radioButton_1024 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_1024.setGeometry(QtCore.QRect(40, 800, 115, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.radioButton_1024.setFont(font)
        self.radioButton_1024.setObjectName("radioButton_1024")
        self.radioButton_2048 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_2048.setGeometry(QtCore.QRect(240, 800, 115, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.radioButton_2048.setFont(font)
        self.radioButton_2048.setObjectName("radioButton_2048")
        self.radioButton_3072 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_3072.setGeometry(QtCore.QRect(430, 800, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.radioButton_3072.setFont(font)
        self.radioButton_3072.setObjectName("radioButton_3072")

        self.retranslateUi(Sign_Up)
        QtCore.QMetaObject.connectSlotsByName(Sign_Up)

    def retranslateUi(self, Sign_Up):
        _translate = QtCore.QCoreApplication.translate
        Sign_Up.setWindowTitle(_translate("Sign_Up", "Form"))
        self.label_Sign_Up.setText(_translate("Sign_Up", "Sign up"))
        self.label_Username.setText(_translate("Sign_Up", "Username*"))
        self.label_Password.setText(_translate("Sign_Up", "Password*"))
        self.pushButton_Sign_Up.setText(_translate("Sign_Up", "Sign up"))
        self.label_Check_Password.setText(_translate("Sign_Up", "Check password*"))
        self.label_Wallet_Private_Key.setText(
            _translate("Sign_Up", "Wallet private key*")
        )
        self.label_Email.setText(_translate("Sign_Up", "Email"))
        self.label_Phone_Number.setText(_translate("Sign_Up", "Phone number"))
        self.lineEdit_Check_Password.setPlaceholderText(
            _translate("Sign_Up", "Make sure your passwords are the same twice")
        )
        self.label_RSA_Key_Pairs_Length.setText(
            _translate("Sign_Up", "Length of RAS key pairs")
        )
        self.label_Have_A_Account.setText(
            _translate("Sign_Up", "Already have an account?")
        )
        self.pushButton_Login.setText(_translate("Sign_Up", "login"))
        self.label_notification.setText(
            _translate(
                "Sign_Up", "Get start private information deliver with your classmate"
            )
        )
        self.radioButton_1024.setText(_translate("Sign_Up", "1024"))
        self.radioButton_2048.setText(_translate("Sign_Up", "2048"))
        self.radioButton_3072.setText(_translate("Sign_Up", "3072"))

    def signUpRequest(self):
        return (
            self.lineEdit_Username.text(),
            self.lineEdit_Password.text(),
            self.lineEdit_Check_Password.text(),
            self.lineEdit_Wallet_Private_Key.text(),
            self.lineEdit_Email.text(),
            self.lineEdit_Phone_Number.text(),
            self.radioButton_1024.isChecked(),
            self.radioButton_2048.isChecked(),
            self.radioButton_3072.isChecked(),
        )

    def show_error(self, error):
        msg_box = QMessageBox()
        msg_box.setWindowTitle("Sign Up Warning")
        msg_box.setText(error)
        msg_box.setIcon(QMessageBox.Critical)
        x = msg_box.exec_()

    def show_info(self, info):
        msg_box = QMessageBox()
        msg_box.setWindowTitle("Sign Up Information")
        msg_box.setText(info)
        x = msg_box.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Sign_Up = QtWidgets.QWidget()
    ui = Ui_Sign_Up()
    ui.setupUi(Sign_Up)
    Sign_Up.show()
    sys.exit(app.exec_())
