# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 signUpButtonEvenis
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Login import Ui_Login


class Ui_Sign_Up(object):
    def setupUi(self, Sign_Up):
        Sign_Up.setObjectName("Sign_Up")
        Sign_Up.resize(556, 931)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        Sign_Up.setFont(font)
        self.label = QtWidgets.QLabel(Sign_Up)
        self.label.setGeometry(QtCore.QRect(230, 0, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Sign_Up)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 141, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Sign_Up)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnSignUp = QtWidgets.QPushButton(Sign_Up)
        self.btnSignUp.setGeometry(QtCore.QRect(40, 870, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.btnSignUp.setFont(font)
        self.btnSignUp.setStyleSheet(
            "color: rgb(255, 255, 255);\n" "background-color: rgb(0, 85, 255);"
        )
        self.btnSignUp.setObjectName("btnSignUp")
        self.btnSignUp.clicked.connect(self.signUpButtonEven)
        self.label_4 = QtWidgets.QLabel(Sign_Up)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.privateKey = QtWidgets.QLabel(Sign_Up)
        self.privateKey.setGeometry(QtCore.QRect(40, 430, 231, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.privateKey.setFont(font)
        self.privateKey.setObjectName("privateKey")
        self.radioButton_size1024 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_size1024.setGeometry(QtCore.QRect(40, 790, 80, 20))
        self.radioButton_size1024.setObjectName("radioButton_size1024")
        self.radioButton_size2048 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_size2048.setGeometry(QtCore.QRect(250, 790, 80, 20))
        self.radioButton_size2048.setObjectName("radioButton_size2048")
        self.radioButton_size3072 = QtWidgets.QRadioButton(Sign_Up)
        self.radioButton_size3072.setGeometry(QtCore.QRect(430, 790, 80, 20))
        self.radioButton_size3072.setObjectName("radioButton_size3072")
        self.label_6 = QtWidgets.QLabel(Sign_Up)
        self.label_6.setGeometry(QtCore.QRect(40, 540, 231, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Sign_Up)
        self.label_7.setGeometry(QtCore.QRect(40, 650, 231, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkPasswordValue = QtWidgets.QLineEdit(Sign_Up)
        self.checkPasswordValue.setGeometry(QtCore.QRect(40, 360, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.checkPasswordValue.setFont(font)
        self.checkPasswordValue.setObjectName("checkPasswordValue")
        self.nameValue = QtWidgets.QLineEdit(Sign_Up)
        self.nameValue.setGeometry(QtCore.QRect(40, 140, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.nameValue.setFont(font)
        self.nameValue.setPlaceholderText("")
        self.nameValue.setObjectName("nameValue")
        self.passwordValue = QtWidgets.QLineEdit(Sign_Up)
        self.passwordValue.setGeometry(QtCore.QRect(40, 250, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.passwordValue.setFont(font)
        self.passwordValue.setPlaceholderText("")
        self.passwordValue.setObjectName("passwordValue")
        self.privateKeyValue = QtWidgets.QLineEdit(Sign_Up)
        self.privateKeyValue.setGeometry(QtCore.QRect(40, 470, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.privateKeyValue.setFont(font)
        self.privateKeyValue.setPlaceholderText("")
        self.privateKeyValue.setObjectName("privateKeyValue")
        self.emailValue = QtWidgets.QLineEdit(Sign_Up)
        self.emailValue.setGeometry(QtCore.QRect(40, 580, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.emailValue.setFont(font)
        self.emailValue.setPlaceholderText("")
        self.emailValue.setObjectName("emailValue")
        self.phonenumberValue = QtWidgets.QLineEdit(Sign_Up)
        self.phonenumberValue.setGeometry(QtCore.QRect(40, 690, 471, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.phonenumberValue.setFont(font)
        self.phonenumberValue.setPlaceholderText("")
        self.phonenumberValue.setObjectName("phonenumberValue")
        self.label_5 = QtWidgets.QLabel(Sign_Up)
        self.label_5.setGeometry(QtCore.QRect(40, 760, 411, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Sign_Up)
        self.label_8.setGeometry(QtCore.QRect(120, 830, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.loginButton = QtWidgets.QPushButton(Sign_Up)
        self.loginButton.setGeometry(QtCore.QRect(320, 830, 61, 31))
        self.loginButton.clicked.connect(self.loginButtonEven)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("color: rgb(85, 170, 255);")
        self.loginButton.setFlat(True)
        self.loginButton.setObjectName("loginButton")
        self.textEdit = QtWidgets.QTextEdit(Sign_Up)
        self.textEdit.setGeometry(QtCore.QRect(120, 50, 351, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Sign_Up)
        QtCore.QMetaObject.connectSlotsByName(Sign_Up)

    def retranslateUi(self, Sign_Up):
        _translate = QtCore.QCoreApplication.translate
        Sign_Up.setWindowTitle(_translate("Sign_Up", "Form"))
        self.label.setText(_translate("Sign_Up", "Sign up"))
        self.label_2.setText(_translate("Sign_Up", "Student Name*"))
        self.label_3.setText(_translate("Sign_Up", "Password*"))
        self.btnSignUp.setText(_translate("Sign_Up", "Sign up"))
        self.label_4.setText(_translate("Sign_Up", "Check password*"))
        self.privateKey.setText(_translate("Sign_Up", "User wallet private key*"))
        self.radioButton_size1024.setText(_translate("Sign_Up", "1024"))
        self.radioButton_size2048.setText(_translate("Sign_Up", "2048"))
        self.radioButton_size3072.setText(_translate("Sign_Up", "3072"))
        self.label_6.setText(_translate("Sign_Up", "Email"))
        self.label_7.setText(_translate("Sign_Up", "Phone number"))
        self.checkPasswordValue.setPlaceholderText(
            _translate("Sign_Up", "Make sure your passwords are the same twice")
        )
        self.label_5.setText(_translate("Sign_Up", "Length of RRAS key pairs"))
        self.label_8.setText(_translate("Sign_Up", "Already have an account?"))
        self.loginButton.setText(_translate("Sign_Up", "login in"))
        self.textEdit.setHtml(
            _translate(
                "Sign_Up",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                "</style></head><body style=\" font-family:'微软雅黑'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:11pt;">Get start private information deliver with your classmate</span></p></body></html>',
            )
        )

    def signUpButtonEven(self):
        print("注册按钮点击")
        print(self.nameValue.text())
        print(
            self.radioButton_size1024.isChecked(),
            self.radioButton_size2048.isChecked(),
            self.radioButton_size3072.isChecked(),
        )

    def loginButtonEven(self):
        print("登陆按钮点击")


import sys

from PyQt5.QtWidgets import QApplication, QMainWindow


def start_ui():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Sign_Up()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


# if __name__ == "__main__":
#     app = QApplication(sys.argv)

#     MainWindow = QMainWindow()

#     ui = Ui_Sign_Up()

#     ui.setupUi(MainWindow)

#     MainWindow.show()

#     sys.exit(app.exec_())
